repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
      types_or: [python]
    - id: trailing-whitespace
      types_or: [python]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.3
  hooks:
    # Run the linter.
    - id: ruff
      stages: [pre-push]
    # Run the formatter.
    - id: ruff-format
      stages: [pre-commit]
