# [build-system]
# requires = ["setuptools>=42", "pybind11>=2.6.1"]
# build-backend = "setuptools.build_meta"

[build-system]
requires = [
    "poetry-core>=1.1.0",
    "setuptools>=65.4.1",
    "pybind11>=2.8.0"
]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name="coolchic"
version="3.3.0"
authors = ["Orange <theo.ladune@orange.com>"]
# url="https://github.com/Orange-OpenSource/Cool-Chic"
description="Cool-Chic: lightweight neural video codec."

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[tool.poetry.dependencies]
python = "^3.12"
torch = ">=2.3.0"
torchvision = "*"
matplotlib = "*"
einops = "*"
fvcore = "*"
cmake = "*"
ConfigArgParse = "*"
psutil = "*"
pytest = "*"
pytest-order = "*"

[tool.poetry.group.dev.dependencies]
ruff = "^0.7.2"

