input: data/kodak/kodim01.png
output: null
workdir: null
disable_wandb: False
load_models: False
user_tag: no-latent-training

enc_cfg:
  start_lr: 1e-2
  n_train_loops: 1
  recipe:
    preset_name: none
    warmup:
      phases:
        - candidates: 5
          training_phase:
            lr: 1e-2
            max_itr: 400
            freq_valid: 400
            patience: 100000
            quantize_model: False
            schedule_lr: False
            softround_temperature: [0.3, 0.3]
            noise_parameter: [2.0, 2.0]
            quantizer_noise_type: "kumaraswamy"
            quantizer_type: "softround"
            optimized_module: ["all"]
        - candidates: 2
          training_phase:
            lr: 1e-2
            max_itr: 400
            freq_valid: 400
            patience: 100000
            quantize_model: False
            schedule_lr: False
            softround_temperature: [0.3, 0.3]
            noise_parameter: [2.0, 2.0]
            quantizer_noise_type: "kumaraswamy"
            quantizer_type: "softround"
            optimized_module: ["all"]
    all_phases:
      - lr: 1e-2
        max_itr: 20000
        patience: 5000
        optimized_module: ["arm", "upsampling", "synthesis"]
        schedule_lr: True
        quantizer_type: softround
        quantizer_noise_type: gaussian
        softround_temperature: [ 0.3, 0.1 ]
        noise_parameter: [ 0.25, 0.1 ]
      - lr: 1e-4
        max_itr: 1500
        patience: 1500
        optimized_module: ["arm", "upsampling", "synthesis"]
        schedule_lr: True
        quantizer_type: ste
        quantizer_noise_type: none
        softround_temperature: [ 1e-4, 1e-4 ]
        noise_parameter: [ 1.0, 1.0 ]
        quantize_model: True 
      - lr: 1e-4
        max_itr: 1000
        patience: 50
        optimized_module: ["arm", "upsampling", "synthesis"]
        quantizer_type: ste
        quantizer_noise_type: none
        freq_valid: 10
        softround_temperature: [ 1e-4, 1e-4 ]
        noise_parameter: [ 1.0, 1.0 ]

dec_cfg:
  - config_name: hop
    arm: 16,2
    layers_synthesis: 48-1-linear-relu,X-1-linear-none,X-3-residual-relu,X-3-residual-none
    n_ft_per_res: 1,1,1,1,1,1,1
    ups_k_size: 8
    ups_preconcat_k_size: 7
