n_samples: 24
batch_size: 4
patch_size: [256, 256]
unfreeze_backbone: 10000
workdir: null
model_weights: __latest
disable_wandb: True
lmbda: 1e-3
user_tag: delta-hn

recipe:
  preset_name: delta hnet training
  warmup:
    empty: True # This is a placeholder for the warmup phase.
  all_phases:
    - lr: 1e-4
      max_itr: 1000
      quantize_model: False
      schedule_lr: True
      end_lr: 1e-6
      softround_temperature: [0.3, 0.1]
      noise_parameter: [1.5, 1.0]
      quantizer_noise_type: "kumaraswamy"
      quantizer_type: "softround"
      patience: 10
      freq_valid: 20
      checkpointing_freq: 100000
      gradient_accumulation: 1

hypernet_cfg:
  synthesis:
    hidden_dim: 1024
    n_layers: 3
    biases: False
  arm:
    hidden_dim: 1024
    n_layers: 3
    biases: False
  upsampling:
    hidden_dim: 256
    n_layers: 1
  backbone_arch: resnet50

  dec_cfg:
    config_name: hop
    arm: 16,2
    layers_synthesis: 48-1-linear-relu,X-1-linear-none,X-3-residual-relu,X-3-residual-none
    n_ft_per_res: 1,1,1,1,1,1,1
    ups_k_size: 8
    ups_preconcat_k_size: 7
