n_samples: 10
batch_size: 2
patch_size: [128, 128]
unfreeze_backbone: 0
workdir: null
disable_wandb: True
lmbda: 1e-3
user_tag: no-cchic-debug

recipe:
  preset_name: NO coolchic hnet debugging
  warmup:
    empty: True # This is a placeholder for the warmup phase.
  all_phases:
    - lr: 1e-3
      max_itr: 100
      quantize_model: False
      schedule_lr: True
      end_lr: 1e-6
      softround_temperature: [0.3, 0.1]
      noise_parameter: [2.0, 1.0]
      quantizer_noise_type: "kumaraswamy"
      quantizer_type: "softround"
      patience: 100
      freq_valid: 10000
      checkpointing_freq: 100000

hypernet_cfg:
  synthesis:
    hidden_dim: 1024
    n_layers: 3
  arm:
    hidden_dim: 1024
    n_layers: 3
  upsampling:
    hidden_dim: 256
    n_layers: 1
  backbone_arch: resnet50
  
  dec_cfg:
    config_name: hop
    arm: 16,2
    layers_synthesis: 48-1-linear-relu,X-1-linear-none,X-3-residual-relu,X-3-residual-none
    n_ft_per_res: 1,1,1,1,1,1,1
    ups_k_size: 8
    ups_preconcat_k_size: 7
